---
- hosts: 10.1.160.100
  gather_facts: no
  tasks:

## THIS BLOCK IS CHECKING THE SERVER REACHABILITY ##

  - block:
    - wait_for_connection:
        timeout: 60
    - setup:
    
    - include_role:
        name: snow_update
        tasks_from: progress
      vars: 
        assign_ansible: "Ansible is checking the status of the dhcp tracing"
    
    rescue:
    - include_role:
        name: snow_update
        tasks_from: failure
      vars: 
        failure_closing_note: "Ansible cannot reach the target server"
        L2_group: "DryIce_CustomerSupportGroup1"
    - fail:
        msg: "Ansible Failed to reach the server"

## THIS BLOCK PERFORMS INCIDENT REMEDIATION STEPS ##

  - block:
    - include_role: 
        name: Dhcp_Tracing_Enable
    
    - include_role:
        name: snow_update
        tasks_from: success
      vars:
        resolve_message: "The dhcpclient tracing has been enabled, hence resolving the ticket"
        success_closing_note: "Incident resolved"
      when: status_code is not defined
    
    - include_role:
        name: snow_update
        tasks_from: transfer
      vars: 
        failure_closing_note: "Ansible failed to enable the dhcpclient tracing on the server, failed to resolve ticket"
        L2_group: "{{ l2_group|default('DryIce_CustomerSupportGroup1') }}"
      when: status_code is defined  ## status_code variable is defined in add_user_linux
    
    rescue:
    - include_role:
        name: snow_update
        tasks_from: failure
      vars: 
        failure_closing_note: "Ansible execution failed on the server as Dhcpclient tracing is already enabled. Incident transferred"
        L2_group: "DryIce_CustomerSupportGroup1"
